spring.application.name=product-service

spring.data.mongodb.uri=mongodb://skipcart_user:skipcart_password123@localhost:27017/skipcart_products?authSource=admin

server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=*

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=300000